### PR TITLE
Remove @available wrappers for Xcode 13

### PR DESCRIPTION
**Pull request by corear**
I just removed the **`@available`** tags that were causing the errors in `/Sources/TeslaEndpoint`. Unsure if this will break the program for older iOS devices, but I think most targets should be of iOS 13 or newer anyway.

### CODE REVIEW

**Comment by jonasman** [comment]
I think you need to remove from other places too. Basically making the lib ios13 min

Sent from my iPhone

On 7 Jul 2021, at 22:25, Collin ***@***.***> wrote:

﻿

I just removed the @available<https://github.com/available> tags that were causing the errors in /Sources/TeslaEndpoint. Unsure if this will break the program for older iOS devices, but I think most targets should be of iOS 13 or newer anyway.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/jonasman/TeslaSwift/pull/100

Commit Summary

  *   Update TeslaEndpoint.swift

File Changes

  *   M Sources/TeslaSwift/TeslaEndpoint.swift<https://github.com/jonasman/TeslaSwift/pull/100/files#diff-b012385eddff4719bd7d80c458370175fa03c27044a6834a8abaa71723c918cb> (2)

Patch Links:

  *   https://github.com/jonasman/TeslaSwift/pull/100.patch
  *   https://github.com/jonasman/TeslaSwift/pull/100.diff

**Comment by corear** [comment]
You're right, I should've checked before. That should be all of them.

**Comment by fuekiin** [comment]
You should increase the min iOS (and macOS, tvOS, watchOS ) version in [Package.swift](https://github.com/jonasman/TeslaSwift/blob/master/Package.swift).

```
platforms: [
        .macOS(.v10_15), .iOS(.v13), .watchOS(.v6), .tvOS(.v13)
    ],
```

**Comment by corear** [comment]
> You should increase the min iOS (and macOS, tvOS, watchOS ) version in [Package.swift](https://github.com/jonasman/TeslaSwift/blob/master/Package.swift).
> 
> ```
> platforms: [
>         .macOS(.v10_15), .iOS(.v13), .watchOS(.v6), .tvOS(.v13)
>     ],
> ```

Good catch. Done 👍

**Comment by jonasman** [comment]
And podfile :D

Sent from my iPhone

On 7 Jul 2021, at 22:59, Collin ***@***.***> wrote:

﻿

You should increase the min iOS (and macOS, tvOS, watchOS ) version in Package.swift<https://github.com/jonasman/TeslaSwift/blob/master/Package.swift>.

platforms: [
        .macOS(.v10_15), .iOS(.v13), .watchOS(.v6), .tvOS(.v13)
    ],


Good catch. Done 👍

**Comment by corear** [comment]
Updated the podspec. Anything else?

**Comment by fuekiin** [comment]
I think you missed the deployment targets in [TeslaSwift.podspec](https://raw.githubusercontent.com/jonasman/TeslaSwift/master/TeslaSwift.podspec)

```
s.ios.deployment_target = '13.0'
s.osx.deployment_target = '10.15'
s.watchos.deployment_target = '6.0'
s.tvos.deployment_target = '13.0'
```

**Comment by corear** [comment]
@jonasman Checking to see if that's all that's needed? :)

**Comment by jonasman** [comment]
I will test later, but for now you can use this branch. I would say let's wait 1 or 2 more betas to see if it gets fixed. Anyway I will probably merge because we cannot use the lib on iOS versions below 13 if login is required

**Comment by corear** [comment]
Okay, sounds good. I'm just not sure how to use this branch instead of your main one in my project with the package dependencies. I'll try to figure it out.

**Comment by RSickenberg** [comment]
Any update on this ?

**Comment by jonasman** [comment]
i need to download xcode, try and merge

**Comment by RSickenberg** [comment]
I'm using this PR for my App, it's safe IMHO.

**Comment by jonasman** [comment]
merged to master, will need to make a new pod version

**Pull request merged**
