### PR TITLE
Added scheduled charging + departure command endpoints

### PR DESCRIPTION
**Pull request by philipengberg**
Added Scheduled charging + Scheduled departure command endpoints. Tested on own car ✅

### CODE REVIEW

**Comment by philipengberg** [comment]
I think we might have different white space settings? You use tabs?

**Comment by philipengberg** [comment]
@jonasman Would you have a look please? 🙂

**Review by jonasman — APPROVED** [review]
looks good

**Comment by jonasman** [comment]
Seems that this PR did not merge correctly

**Pull request merged**
